# Generated by Django 6.0.8 on 2026-08-18 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.CharField(blank=True, default="", max_length=500)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "info"),
                            ("success", "success"),
                            ("warning", "warning"),
                            ("error", "error"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("kind", models.CharField(default="system", max_length=20)),
                ("paper_id", models.BigIntegerField(blank=True, null=True)),
                ("job_id", models.BigIntegerField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_notifications",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-id"],
                        name="user_notifi_user_id_813707_idx",
                    ),
                    models.Index(
                        fields=["user", "job_id"], name="user_notifi_user_id_d02de6_idx"
                    ),
                ],
            },
        ),
    ]
