# Generated by Django 6.0.8 on 2026-08-19 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal


def seed_plans(apps, schema_editor):
    MembershipPlan = apps.get_model('accounts', 'MembershipPlan')
    rows = [
        ('free', '未开通会员', 1, 1, 10, Decimal('0'), 0, False, 0),
        ('basic', '普通会员', 1, 1, 10, Decimal('0'), 0, True, 1),
        ('baijin', '白金会员', 10, 10, 10, Decimal('20'), 0, True, 2),
        ('gold', '黄金会员', 20, 20, 15, Decimal('30'), 0, True, 3),
        ('platinum', '铂金会员', 20, 20, 20, Decimal('40'), 5, True, 4),
        ('diamond', '钻石会员', 30, 30, 30, Decimal('50'), -1, True, 5),
    ]
    for code, name, tr, pr, pages, price, share, buy, sort in rows:
        MembershipPlan.objects.get_or_create(
            code=code,
            defaults={
                'name': name, 'daily_translate': tr, 'daily_parse': pr,
                'page_limit': pages, 'price_month': price,
                'team_share_limit': share, 'purchasable': buy, 'sort': sort,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usernotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=40)),
                ("daily_translate", models.IntegerField(default=1)),
                ("daily_parse", models.IntegerField(default=1)),
                ("page_limit", models.IntegerField(default=10)),
                (
                    "price_month",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("team_share_limit", models.IntegerField(default=0)),
                ("purchasable", models.BooleanField(default=True)),
                ("sort", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "membership_plans",
                "ordering": ["sort", "id"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="membership_expire_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="quota_page_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="quota_parse_daily",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="quota_team_share",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="quota_translate_daily",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MembershipOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("months", models.PositiveSmallIntegerField(default=1)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("paid", "paid"),
                            ("cancelled", "cancelled"),
                        ],
                        default="paid",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="accounts.membershipplan",
                    ),
                ),
            ],
            options={
                "db_table": "membership_orders",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="membership_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.membershipplan",
            ),
        ),
        migrations.CreateModel(
            name="DailyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("translate_ids", models.JSONField(blank=True, default=list)),
                ("parse_ids", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_usages",
                "unique_together": {("user", "day")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("team_share_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "monthly_usages",
                "unique_together": {("user", "year", "month")},
            },
        ),
        migrations.RunPython(seed_plans, migrations.RunPython.noop),
    ]
