# Generated by Django 6.0.8 on 2026-08-19 01:40

import hashlib

from django.db import migrations, models


def fill_trade_nos(apps, schema_editor):
    MembershipOrder = apps.get_model('accounts', 'MembershipOrder')
    for order in MembershipOrder.objects.all():
        if order.trade_no:
            continue
        stamp = (order.created_at or order.paid_at)
        stamp_s = stamp.strftime('%Y%m%d%H%M%S') if stamp else '19700101000000'
        tail = hashlib.md5(f'{order.id}-{stamp_s}'.encode()).hexdigest()[:8].upper()
        order.trade_no = f'PM{stamp_s}{order.id:06d}{tail}'[:40]
        order.save(update_fields=['trade_no'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiporder',
            name='channel',
            field=models.CharField(
                choices=[('alipay', '支付宝'), ('wechat', '微信支付')],
                default='alipay',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='membershiporder',
            name='trade_no',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.RunPython(fill_trade_nos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='membershiporder',
            name='trade_no',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='membershiporder',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'pending'),
                    ('paid', 'paid'),
                    ('cancelled', 'cancelled'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]
