# Generated by Django 6.0.8 on 2026-08-17 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("papers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OcrRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.CharField(max_length=500)),
                ("rect", models.CharField(blank=True, max_length=50, null=True)),
                ("ocr_text", models.TextField()),
                ("ai_translation", models.TextField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True, null=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_records",
                        to="papers.paper",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ocr_records",
            },
        ),
        migrations.CreateModel(
            name="PaperHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("para_index", models.IntegerField()),
                ("sel_text", models.CharField(max_length=1000)),
                ("color", models.CharField(default="y", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="papers.paper",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "paper_highlights",
            },
        ),
        migrations.CreateModel(
            name="PaperNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sel_text", models.CharField(blank=True, max_length=1000, null=True)),
                ("note_text", models.TextField(blank=True, null=True)),
                ("ai_translation", models.TextField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True, null=True)),
                ("source", models.CharField(default="selection", max_length=20)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "公开"),
                            ("friends", "仅好友"),
                            ("private", "私密"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "ocr_image_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("ocr_rect", models.CharField(blank=True, max_length=50, null=True)),
                ("para_index", models.IntegerField(blank=True, null=True)),
                ("like_count", models.IntegerField(default=0)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("team_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "highlight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reader.paperhighlight",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="papers.paper",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "paper_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term_en", models.CharField(max_length=200)),
                ("term_zh", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("team_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terms",
                        to="papers.paper",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glossary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "glossary_terms",
                "unique_together": {("user", "term_en")},
            },
        ),
        migrations.CreateModel(
            name="ParagraphTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("para_index", models.IntegerField()),
                ("text_hash", models.CharField(max_length=64)),
                ("source_text", models.TextField()),
                ("translated_text", models.TextField()),
                ("engine", models.CharField(default="deepseek", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="papers.paper",
                    ),
                ),
            ],
            options={
                "db_table": "paragraph_translations",
                "unique_together": {("paper", "para_index", "text_hash")},
            },
        ),
        migrations.CreateModel(
            name="ReadingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                (
                    "last_section",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_position", models.IntegerField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_records",
                        to="papers.paper",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reading_records",
                "unique_together": {("user", "paper")},
            },
        ),
    ]
