# Generated by Django 6.0.8 on 2026-08-17 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("sort", models.IntegerField(default=0)),
                ("is_system", models.BooleanField(default=False)),
                ("team_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "categories",
                "ordering": ["sort", "id"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("title_zh", models.CharField(blank=True, max_length=500, null=True)),
                ("authors", models.CharField(blank=True, max_length=500, null=True)),
                ("venue", models.CharField(blank=True, max_length=200, null=True)),
                ("year", models.SmallIntegerField(blank=True, null=True)),
                ("doi", models.CharField(blank=True, max_length=100, null=True)),
                ("arxiv_id", models.CharField(blank=True, max_length=50, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("abstract_zh", models.TextField(blank=True, null=True)),
                ("intro", models.CharField(blank=True, max_length=1000, null=True)),
                ("tags", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("想读", "想读"), ("在读", "在读"), ("读完", "读完")],
                        default="想读",
                        max_length=20,
                    ),
                ),
                ("starred", models.BooleanField(default=False)),
                ("read_progress", models.PositiveSmallIntegerField(default=0)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("file", "file"),
                            ("doi", "doi"),
                            ("arxiv", "arxiv"),
                            ("site", "site"),
                            ("graph", "graph"),
                            ("share", "share"),
                        ],
                        default="file",
                        max_length=20,
                    ),
                ),
                ("file_type", models.CharField(blank=True, max_length=10, null=True)),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("cover_url", models.CharField(blank=True, max_length=500, null=True)),
                ("cites", models.IntegerField(default=0)),
                ("content_json", models.JSONField(blank=True, null=True)),
                ("outline", models.JSONField(blank=True, null=True)),
                ("ai_summary", models.JSONField(blank=True, null=True)),
                ("share_type", models.CharField(default="private", max_length=20)),
                ("team_id", models.BigIntegerField(blank=True, null=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="papers",
                        to="papers.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "papers",
                "ordering": ["-last_read_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ImportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("import_type", models.CharField(max_length=20)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("error_msg", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="papers.paper",
                    ),
                ),
            ],
            options={
                "db_table": "import_records",
            },
        ),
        migrations.CreateModel(
            name="PaperFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_type", models.CharField(max_length=10)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="papers.paper",
                    ),
                ),
            ],
            options={
                "db_table": "paper_files",
            },
        ),
        migrations.CreateModel(
            name="PaperShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_type", models.CharField(max_length=10)),
                ("target_team_id", models.BigIntegerField(blank=True, null=True)),
                ("message", models.CharField(blank=True, max_length=500, null=True)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="papers.paper",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "paper_shares",
            },
        ),
        migrations.CreateModel(
            name="UserSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.CharField(max_length=500)),
                ("icon", models.CharField(blank=True, max_length=200, null=True)),
                ("source_type", models.CharField(default="builtin", max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                ("sort", models.IntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("team_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_sources",
                "ordering": ["sort", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["user", "status"], name="papers_user_id_313506_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["user", "category"], name="papers_user_id_2e1a83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=models.Index(
                fields=["user", "starred"], name="papers_user_id_d71d3e_idx"
            ),
        ),
    ]
