# Generated by Django 6.0.8 on 2026-08-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="layout_meta",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
